<a href="https://colab.research.google.com/github/jaylakebrains/TensorFlow-Learning/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensorflow Fundamentals**


In [3]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [4]:
tensor = tf.constant([7, 8])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 8], dtype=int32)>

In [5]:
tensor.ndim


1

In [6]:
matrix = tf.constant([[1,2],
                      [3,4]])

In [7]:
matrix.ndim


2

In [8]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [9]:
changeable_tensor[0].assign(7)  

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [10]:
# creating random tensors
r1 = tf.random.Generator.from_seed(32)
r1 = r1.normal(shape=(3, 2))
r1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.7901182 ,  1.585549  ],
       [ 0.4356279 ,  0.23645182],
       [-0.1589871 ,  1.302304  ]], dtype=float32)>

In [11]:
r2 = tf.random.Generator.from_seed(12)
r2 = r2.normal(shape=(3, 2))
r2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.0130816 ,  0.28291714],
       [ 1.2132233 ,  0.46988967],
       [ 0.37944323, -0.6664026 ]], dtype=float32)>

In [12]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled, seed = 66)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

Diffrent way to make tensors

In [13]:
tf.ones(shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [14]:
tf.zeros(shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

Using NumPy

In [15]:
import numpy as np
arr = np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
tensor_arr = tf.constant(arr, shape= [2,4,3])
tensor_arr

<tf.Tensor: shape=(2, 4, 3), dtype=int64, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>


Getting information from tensors (shape, rank, size)

In [17]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)


(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [19]:
rank_4_tensor[:2, :2, :2, :2]
# slicing_matrix

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [21]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # in Python "..." means "all dimensions prior to"
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [22]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>


Manipulating tensors (tensor operations)
---



In [23]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [24]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [25]:
tf.multiply(tensor, 10)
# Alternate

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Matrix mutliplication

In [26]:
print(matrix)
matrix @ matrix

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [27]:
tf.matmul(matrix, [[2,3],[6,8]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 19],
       [30, 41]], dtype=int32)>

In [28]:
tf.matmul(matrix, matrix)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [29]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

Reshape Matrix

In [30]:
X = tf.reshape(X, shape=(2, 3))


In [31]:
Z = X @ Y
Z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

Transpose

In [32]:
tf.transpose(Z)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58, 139],
       [ 64, 154]], dtype=int32)>

In [33]:
tf.tensordot(X, Y, axes=1)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [34]:
A = tf.constant([7,9,2,5])
B = tf.constant([-9,4,1.4,8.6])
A,B

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([7, 9, 2, 5], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-9. ,  4. ,  1.4,  8.6], dtype=float32)>)

In [35]:
B = tf.cast(B, dtype = tf.int16)
B

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([-9,  4,  1,  8], dtype=int16)>

Get Absolute Variable

In [36]:
tf.abs(B)

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([9, 4, 1, 8], dtype=int16)>

Finding the min, max, mean, sum (aggregation)


In [37]:
C = tf.constant(np.random.randint(low=1, high=100, size=50))
C

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([73, 40, 11, 50, 62, 52, 18, 37, 34, 32, 51, 85, 74, 74, 28, 65, 60,
       45,  6, 13, 25, 96, 14, 53, 20, 78, 88, 22, 52, 65, 26, 15, 59, 44,
       94, 47, 23, 68, 43, 94, 95, 72, 75, 79, 69, 62, 87, 59,  2, 77])>

In [38]:
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [39]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [40]:
tf.reduce_mean(C)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [41]:
tf.reduce_sum(C)

<tf.Tensor: shape=(), dtype=int64, numpy=2613>

**Finding the positional maximum and minimum**

tf.argmax() - find the position of the maximum element in a given tensor.

tf.argmin() - find the position of the minimum element in a given tensor.

Squeezing

In [42]:
tf.argmax(C)

<tf.Tensor: shape=(), dtype=int64, numpy=21>

In [43]:
tf.argmin(C)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [54]:
tf.squeeze(C)
"""C = [73, 40, 11, 50, 62, 52, 18, 37, 34, 32, 51, 85, 74, 74, 28, 65, 60,
       45,  6, 13, 25, 96, 14, 53, 20, 78, 88, 22, 52, 65, 26, 15, 59, 44,
       94, 47, 23, 68, 43, 94, 95, 72, 75, 79, 69, 62, 87, 59,  2, 77]"""

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([73, 40, 11, 50, 62, 52, 18, 37, 34, 32, 51, 85, 74, 74, 28, 65, 60,
       45,  6, 13, 25, 96, 14, 53, 20, 78, 88, 22, 52, 65, 26, 15, 59, 44,
       94, 47, 23, 68, 43, 94, 95, 72, 75, 79, 69, 62, 87, 59,  2, 77])>

**One-hot encoding**

In [45]:
# Create a list of indices
lst = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(lst, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [46]:
tf.one_hot(lst, depth=4, on_value="online", off_value="Offline")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'online', b'Offline', b'Offline', b'Offline'],
       [b'Offline', b'online', b'Offline', b'Offline'],
       [b'Offline', b'Offline', b'online', b'Offline'],
       [b'Offline', b'Offline', b'Offline', b'online']], dtype=object)>

Squaring, log, square root

In [47]:
tf.square(C)


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([5329, 1600,  121, 2500, 3844, 2704,  324, 1369, 1156, 1024, 2601,
       7225, 5476, 5476,  784, 4225, 3600, 2025,   36,  169,  625, 9216,
        196, 2809,  400, 6084, 7744,  484, 2704, 4225,  676,  225, 3481,
       1936, 8836, 2209,  529, 4624, 1849, 8836, 9025, 5184, 5625, 6241,
       4761, 3844, 7569, 3481,    4, 5929])>

In [48]:
# tf.sqrt(C)
tf.cast(C, dtype = tf.float32)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([73., 40., 11., 50., 62., 52., 18., 37., 34., 32., 51., 85., 74.,
       74., 28., 65., 60., 45.,  6., 13., 25., 96., 14., 53., 20., 78.,
       88., 22., 52., 65., 26., 15., 59., 44., 94., 47., 23., 68., 43.,
       94., 95., 72., 75., 79., 69., 62., 87., 59.,  2., 77.],
      dtype=float32)>

tf.function

In [49]:
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [50]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

**Finding access to GPUs** 

In [51]:
# print(tf.config.list_physical_devices('GPU'))


In [52]:
# !nvidia-smi


Reference URL = https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/00_tensorflow_fundamentals.ipynb